Update Django deploy check command

diff --git a/.github/workflows/django_check_deploy.yml b/.github/workflows/django_check_deploy.yml
--- a/.github/workflows/django_check_deploy.yml
+++ b/.github/workflows/django_check_deploy.yml
@@ -22,4 +22,8 @@ jobs:
 
     - name: Django Deploy Check
       run: |
-        python src/manage.py check --deploy
+        python -m django check --deploy
+        if [[ $? -ne 0 ]]; then
+          echo "Django check --deploy failed with warnings"
+          exit 1
+        fi
